---
- name: Generate hosts file
  hosts: all
  become: true

  tasks:
    - name: create /etc/myhosts file
      template:
        #src: ./template/hosts.j2
        src: ./template/jinja.j2
        dest: /etc/myhosts
        owner: root
        group: root
        mode: '0644'
