---
- name: Manage timesync with 3 servers
  hosts: all
  vars:
    timesync_ntp_servers:
      - hostname: 192.168.10.54
        iburst: true
      - hostname: 192.168.10.58
        iburst: true
  roles:
    - rhel-system-roles.timesync
